version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "auto-merge"
    groups:
      patch-and-minor:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci"
